services:
  api:
    build:
      context: .
      network: host
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G
    depends_on:
      - postgres-db
      - pgvector-db
      - mongodb

  pgvector-db:
    image: pgvector/pgvector:pg16
    ports:
      - "6026:5432"
    env_file:
      - .env.docker
    volumes:
      - pgvector-data:/var/lib/postgresql/data

  postgres-db:
    image: postgres:latest
    ports:
      - "6027:5432"
    env_file:
      - .env.docker
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongodb:
    image: mongodb/mongodb-community-server:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    env_file:
      - .env.docker

  ollama:
    container_name: ollama
    image: ollama/ollama:latest 
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: ["gpu"]
            count: all
    volumes:
      - ollama:/root/.ollama
    restart: always

volumes:
  pgvector-data:
  postgres-data:
  mongodb-data:
  ollama: